# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Binomial.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(639, 329)
        self.btnCalcular = QtWidgets.QPushButton(Dialog)
        self.btnCalcular.setGeometry(QtCore.QRect(410, 170, 111, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcular.setFont(font)
        self.btnCalcular.setObjectName("btnCalcular")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnEliminarFilas = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminarFilas.setFont(font)
        self.btnEliminarFilas.setObjectName("btnEliminarFilas")
        self.verticalLayout.addWidget(self.btnEliminarFilas)
        self.tablaBinomial = QtWidgets.QTableWidget(self.layoutWidget)
        self.tablaBinomial.setObjectName("tablaBinomial")
        self.tablaBinomial.setColumnCount(3)
        self.tablaBinomial.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaBinomial.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaBinomial.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaBinomial.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tablaBinomial)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(374, 40, 251, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtExito = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtExito.setFont(font)
        self.txtExito.setObjectName("txtExito")
        self.gridLayout.addWidget(self.txtExito, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtEnsayo = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtEnsayo.setFont(font)
        self.txtEnsayo.setObjectName("txtEnsayo")
        self.gridLayout.addWidget(self.txtEnsayo, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtProbabilidad = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtProbabilidad.setFont(font)
        self.txtProbabilidad.setObjectName("txtProbabilidad")
        self.gridLayout.addWidget(self.txtProbabilidad, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtExito, self.txtEnsayo)
        Dialog.setTabOrder(self.txtEnsayo, self.txtProbabilidad)
        Dialog.setTabOrder(self.txtProbabilidad, self.btnCalcular)
        Dialog.setTabOrder(self.btnCalcular, self.btnEliminarFilas)
        Dialog.setTabOrder(self.btnEliminarFilas, self.tablaBinomial)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Distribución Binomial"))
        self.btnCalcular.setText(_translate("Dialog", "Calcular"))
        self.btnEliminarFilas.setText(_translate("Dialog", "Limpiar Campos"))
        item = self.tablaBinomial.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Ensayo"))
        item = self.tablaBinomial.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Probabilidad"))
        item = self.tablaBinomial.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Acumulada"))
        self.label.setText(_translate("Dialog", "Número de Éxitos:"))
        self.label_2.setText(_translate("Dialog", "Número de Ensayos:"))
        self.label_3.setText(_translate("Dialog", "Probabilidad de Éxito:"))

