# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exponencial.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(706, 480)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(470, 60, 210, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(480, 130, 173, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 10, 431, 451))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnEliminaFila = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminaFila.setFont(font)
        self.btnEliminaFila.setObjectName("btnEliminaFila")
        self.gridLayout_4.addWidget(self.btnEliminaFila, 0, 0, 1, 1)
        self.tablaExponencial = QtWidgets.QTableWidget(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tablaExponencial.setFont(font)
        self.tablaExponencial.setObjectName("tablaExponencial")
        self.tablaExponencial.setColumnCount(4)
        self.tablaExponencial.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaExponencial.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaExponencial.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaExponencial.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaExponencial.setHorizontalHeaderItem(3, item)
        self.gridLayout_4.addWidget(self.tablaExponencial, 1, 0, 1, 1)
        self.btnCalcular = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcular.setFont(font)
        self.btnCalcular.setObjectName("btnCalcular")
        self.gridLayout_4.addWidget(self.btnCalcular, 2, 0, 1, 1)
        self.txtNumero = QtWidgets.QSpinBox(Dialog)
        self.txtNumero.setGeometry(QtCore.QRect(540, 160, 61, 22))
        self.txtNumero.setObjectName("txtNumero")
        self.txtMedia = QtWidgets.QDoubleSpinBox(Dialog)
        self.txtMedia.setGeometry(QtCore.QRect(540, 90, 62, 22))
        self.txtMedia.setObjectName("txtMedia")
        self.btnGenerar = QtWidgets.QPushButton(Dialog)
        self.btnGenerar.setGeometry(QtCore.QRect(500, 210, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnGenerar.setFont(font)
        self.btnGenerar.setObjectName("btnGenerar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtMedia, self.txtNumero)
        Dialog.setTabOrder(self.txtNumero, self.btnCalcular)
        Dialog.setTabOrder(self.btnCalcular, self.btnEliminaFila)
        Dialog.setTabOrder(self.btnEliminaFila, self.tablaExponencial)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Distribución Exponencial"))
        self.label_2.setText(_translate("Dialog", "Media de Ocurrencias (Lambda):"))
        self.label.setText(_translate("Dialog", "Número de Ocurrencia (X):"))
        self.btnEliminaFila.setText(_translate("Dialog", "Limpiar Campos"))
        item = self.tablaExponencial.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "X"))
        item = self.tablaExponencial.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Aleatorio"))
        item = self.tablaExponencial.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Exponencial"))
        item = self.tablaExponencial.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Exponencial (1-r)"))
        self.btnCalcular.setText(_translate("Dialog", "Calcular"))
        self.btnGenerar.setText(_translate("Dialog", "Ingresar Valores"))

