# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Multiplicativo.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 450)
        Dialog.setWindowOpacity(1.0)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnEliminarFilas = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminarFilas.setFont(font)
        self.btnEliminarFilas.setObjectName("btnEliminarFilas")
        self.gridLayout.addWidget(self.btnEliminarFilas, 0, 0, 1, 1)
        self.tablaMultiplicativo = QtWidgets.QTableWidget(self.layoutWidget)
        self.tablaMultiplicativo.setObjectName("tablaMultiplicativo")
        self.tablaMultiplicativo.setColumnCount(5)
        self.tablaMultiplicativo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaMultiplicativo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaMultiplicativo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaMultiplicativo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaMultiplicativo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaMultiplicativo.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tablaMultiplicativo, 1, 0, 1, 1)
        self.btnCalcular = QtWidgets.QPushButton(Dialog)
        self.btnCalcular.setGeometry(QtCore.QRect(220, 420, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcular.setFont(font)
        self.btnCalcular.setObjectName("btnCalcular")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(168, 290, 171, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.txtA = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtA.setFont(font)
        self.txtA.setObjectName("txtA")
        self.gridLayout_2.addWidget(self.txtA, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtXn = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtXn.setFont(font)
        self.txtXn.setObjectName("txtXn")
        self.gridLayout_2.addWidget(self.txtXn, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtM = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtM.setFont(font)
        self.txtM.setObjectName("txtM")
        self.gridLayout_2.addWidget(self.txtM, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.txtN = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtN.setFont(font)
        self.txtN.setObjectName("txtN")
        self.gridLayout_2.addWidget(self.txtN, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtA, self.txtXn)
        Dialog.setTabOrder(self.txtXn, self.txtM)
        Dialog.setTabOrder(self.txtM, self.txtN)
        Dialog.setTabOrder(self.txtN, self.btnCalcular)
        Dialog.setTabOrder(self.btnCalcular, self.btnEliminarFilas)
        Dialog.setTabOrder(self.btnEliminarFilas, self.tablaMultiplicativo)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Congruencial Multiplicativo"))
        self.btnEliminarFilas.setText(_translate("Dialog", "Limpiar Campos"))
        item = self.tablaMultiplicativo.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "n"))
        item = self.tablaMultiplicativo.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Xn"))
        item = self.tablaMultiplicativo.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "aXn"))
        item = self.tablaMultiplicativo.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "(aXn) Mod(m)"))
        item = self.tablaMultiplicativo.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Aleatorio"))
        self.btnCalcular.setText(_translate("Dialog", "Calcular"))
        self.label.setText(_translate("Dialog", "Multiplicador (a):"))
        self.label_2.setText(_translate("Dialog", "Semilla (Xn):"))
        self.label_3.setText(_translate("Dialog", "Módulo (m):"))
        self.label_4.setText(_translate("Dialog", "Eventos (n):"))

