# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Normal.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(735, 327)
        self.btnIngresar = QtWidgets.QPushButton(Dialog)
        self.btnIngresar.setGeometry(QtCore.QRect(510, 180, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnIngresar.setFont(font)
        self.btnIngresar.setObjectName("btnIngresar")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnEliminarFilas = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminarFilas.setFont(font)
        self.btnEliminarFilas.setFlat(False)
        self.btnEliminarFilas.setObjectName("btnEliminarFilas")
        self.verticalLayout.addWidget(self.btnEliminarFilas)
        self.tablaNormal = QtWidgets.QTableWidget(self.layoutWidget)
        self.tablaNormal.setObjectName("tablaNormal")
        self.tablaNormal.setColumnCount(4)
        self.tablaNormal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaNormal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaNormal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaNormal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaNormal.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tablaNormal)
        self.btnCalcular = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcular.setFont(font)
        self.btnCalcular.setStatusTip("")
        self.btnCalcular.setAutoDefault(True)
        self.btnCalcular.setDefault(False)
        self.btnCalcular.setFlat(False)
        self.btnCalcular.setObjectName("btnCalcular")
        self.verticalLayout.addWidget(self.btnCalcular)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(460, 40, 241, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.txtDesviacion = QtWidgets.QSpinBox(self.layoutWidget1)
        self.txtDesviacion.setObjectName("txtDesviacion")
        self.gridLayout.addWidget(self.txtDesviacion, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtMedia = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.txtMedia.setObjectName("txtMedia")
        self.gridLayout.addWidget(self.txtMedia, 0, 2, 1, 1)
        self.txtEvento = QtWidgets.QSpinBox(self.layoutWidget1)
        self.txtEvento.setObjectName("txtEvento")
        self.gridLayout.addWidget(self.txtEvento, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtMedia, self.txtDesviacion)
        Dialog.setTabOrder(self.txtDesviacion, self.txtEvento)
        Dialog.setTabOrder(self.txtEvento, self.btnIngresar)
        Dialog.setTabOrder(self.btnIngresar, self.btnCalcular)
        Dialog.setTabOrder(self.btnCalcular, self.btnEliminarFilas)
        Dialog.setTabOrder(self.btnEliminarFilas, self.tablaNormal)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Distribución Normal"))
        self.btnIngresar.setText(_translate("Dialog", "Ingresar Valores"))
        self.btnEliminarFilas.setText(_translate("Dialog", "Limpiar Campos"))
        item = self.tablaNormal.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Evento"))
        item = self.tablaNormal.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Aleatorio"))
        item = self.tablaNormal.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Z"))
        item = self.tablaNormal.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "P"))
        self.btnCalcular.setText(_translate("Dialog", "Calcular"))
        self.label.setText(_translate("Dialog", "Media µ:"))
        self.label_2.setText(_translate("Dialog", "Desviación Estandar:"))
        self.label_3.setText(_translate("Dialog", "Eventos:"))

