# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PromedioMovil.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(475, 536)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnEliminaFila = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminaFila.setFont(font)
        self.btnEliminaFila.setObjectName("btnEliminaFila")
        self.verticalLayout.addWidget(self.btnEliminaFila)
        self.tablaProMovil = QtWidgets.QTableWidget(self.layoutWidget)
        self.tablaProMovil.setObjectName("tablaProMovil")
        self.tablaProMovil.setColumnCount(4)
        self.tablaProMovil.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaProMovil.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaProMovil.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaProMovil.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaProMovil.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tablaProMovil)
        self.btnCalcular = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcular.setFont(font)
        self.btnCalcular.setObjectName("btnCalcular")
        self.verticalLayout.addWidget(self.btnCalcular)
        self.btnIngresar = QtWidgets.QPushButton(Dialog)
        self.btnIngresar.setGeometry(QtCore.QRect(140, 480, 161, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnIngresar.setFont(font)
        self.btnIngresar.setObjectName("btnIngresar")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(69, 420, 141, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtEvento = QtWidgets.QSpinBox(self.layoutWidget1)
        self.txtEvento.setObjectName("txtEvento")
        self.horizontalLayout.addWidget(self.txtEvento)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(240, 420, 121, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtMovil = QtWidgets.QSpinBox(self.layoutWidget2)
        self.txtMovil.setObjectName("txtMovil")
        self.horizontalLayout_2.addWidget(self.txtMovil)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtEvento, self.txtMovil)
        Dialog.setTabOrder(self.txtMovil, self.btnIngresar)
        Dialog.setTabOrder(self.btnIngresar, self.btnCalcular)
        Dialog.setTabOrder(self.btnCalcular, self.btnEliminaFila)
        Dialog.setTabOrder(self.btnEliminaFila, self.tablaProMovil)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Promedio Móvil"))
        self.btnEliminaFila.setText(_translate("Dialog", "Limpiar Campos"))
        item = self.tablaProMovil.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Evento"))
        item = self.tablaProMovil.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Acción"))
        item = self.tablaProMovil.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Móvil"))
        item = self.tablaProMovil.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Diferencia"))
        self.btnCalcular.setText(_translate("Dialog", "&Calcular"))
        self.btnIngresar.setText(_translate("Dialog", "Ingresar Eventos "))
        self.label.setText(_translate("Dialog", "Eventos:"))
        self.label_2.setText(_translate("Dialog", "Móvil:"))

