# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Uniforme.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(666, 485)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 361, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnEliminaFila = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminaFila.setFont(font)
        self.btnEliminaFila.setObjectName("btnEliminaFila")
        self.gridLayout_4.addWidget(self.btnEliminaFila, 0, 0, 1, 1)
        self.tablaUniforme = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablaUniforme.sizePolicy().hasHeightForWidth())
        self.tablaUniforme.setSizePolicy(sizePolicy)
        self.tablaUniforme.setMaximumSize(QtCore.QSize(329, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tablaUniforme.setFont(font)
        self.tablaUniforme.setObjectName("tablaUniforme")
        self.tablaUniforme.setColumnCount(3)
        self.tablaUniforme.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaUniforme.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaUniforme.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablaUniforme.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.tablaUniforme, 1, 0, 1, 1)
        self.btnCalcular = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcular.setFont(font)
        self.btnCalcular.setObjectName("btnCalcular")
        self.gridLayout_4.addWidget(self.btnCalcular, 2, 0, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(360, 130, 291, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.txtEvento = QtWidgets.QSpinBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtEvento.setFont(font)
        self.txtEvento.setObjectName("txtEvento")
        self.gridLayout.addWidget(self.txtEvento, 0, 1, 1, 1)
        self.btnGenerar = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnGenerar.setFont(font)
        self.btnGenerar.setObjectName("btnGenerar")
        self.gridLayout.addWidget(self.btnGenerar, 0, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(410, 50, 151, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtNumA = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtNumA.setFont(font)
        self.txtNumA.setObjectName("txtNumA")
        self.gridLayout_7.addWidget(self.txtNumA, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.txtNumB = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtNumB.setFont(font)
        self.txtNumB.setObjectName("txtNumB")
        self.gridLayout_7.addWidget(self.txtNumB, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtNumA, self.txtNumB)
        Dialog.setTabOrder(self.txtNumB, self.txtEvento)
        Dialog.setTabOrder(self.txtEvento, self.btnGenerar)
        Dialog.setTabOrder(self.btnGenerar, self.btnCalcular)
        Dialog.setTabOrder(self.btnCalcular, self.btnEliminaFila)
        Dialog.setTabOrder(self.btnEliminaFila, self.tablaUniforme)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Distribución Uniforme"))
        self.btnEliminaFila.setText(_translate("Dialog", "Limpiar Campos"))
        item = self.tablaUniforme.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Evento"))
        item = self.tablaUniforme.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Aleatorio"))
        item = self.tablaUniforme.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Uniforme"))
        self.btnCalcular.setText(_translate("Dialog", "&Calcular"))
        self.label_3.setText(_translate("Dialog", "Número de Eventos:"))
        self.btnGenerar.setText(_translate("Dialog", "Generar"))
        self.label_2.setText(_translate("Dialog", "Ingrese A:"))
        self.label_5.setText(_translate("Dialog", "Ingrese B:"))

